trigger:
- none

pool:
  name: ArmPool

stages:
- stage: Test
  displayName: Test
  jobs:
  - job: TestJob
    steps:
    - task: Bash@3
      displayName: Clean Install
      inputs:
        targetType: 'inline'
        script: 'npm ci'
        workingDirectory: '$(System.DefaultWorkingDirectory)/client'
    - task: Bash@3
      displayName: Run Tests
      inputs:
        targetType: 'inline'
        script: 'CI=true npm test'
        workingDirectory: '$(System.DefaultWorkingDirectory)/client'

- stage: Build
  displayName: Build
  jobs:
  - job: Build
    steps:
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'dockerhub-ahmedavid'
    #     repository: 'ahmedavid/notedown-react'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     buildContext: 'client'
    #     tags: |
    #       $(Build.BuildId)
    #       latest
    - task: DownloadSecureFile@1
      displayName: Download Kube Config
      name: kubeconfig
      inputs:
        secureFile: 'kubeconfig'
    - task: KubectlInstaller@0
      displayName: Install Kubectl
      inputs:
        kubectlVersion: 'latest'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'kubectl --kubeconfig=$(kubeconfig.secureFilePath) get all -A'
    # - task: KubernetesManifest@1
    #   inputs:
    #     action: 'deploy'
    #     connectionType: 'kubernetesServiceConnection'
    #     namespace: 'notedown'
    # - task: PublishTestResults@2
    #   inputs:
    #     testResultsFormat: 'JUnit'
    #     testResultsFiles: |
    #       junit.xml
    #       **/*junit*.xml
    #     failTaskOnFailedTests: true
