trigger:
- none

pool:
  name: ArmPool

stages:
- stage: Test
  displayName: Run React Tests
  jobs:
  - job: TestJob
    steps:
    - task: Npm@1
      inputs:
        command: 'ci'
        workingDir: 'client'
    - task: Npm@1
      inputs:
        command: 'custom'
        workingDir: 'client'
        customCommand: 'test -- --watchAll=false'
