trigger:
  branches:
    include:
      - main
  paths:
    include:
      - client/**

pool:
  name: ArmPool

stages:
  - stage: Test
    condition: 
    displayName: Test
    jobs:
      - job: TestJob
        steps:
          - task: Bash@3
            displayName: Clean Install
            inputs:
              targetType: "inline"
              script: "npm ci"
              workingDirectory: "$(System.DefaultWorkingDirectory)/client"
          - task: Bash@3
            displayName: Run Tests
            inputs:
              targetType: "inline"
              script: "CI=true npm test"
              workingDirectory: "$(System.DefaultWorkingDirectory)/client"

  - stage: Build
    displayName: Build
    jobs:
      - job: Build
        steps:
          - task: Docker@2
            displayName: Build Docker Image
            inputs:
              containerRegistry: "dockerhub-ahmedavid"
              repository: "ahmedavid/notedown-react"
              command: "buildAndPush"
              Dockerfile: "**/Dockerfile"
              buildContext: "client"
              tags: |
                $(Build.BuildId)
                latest
  - stage: Publish
    condition: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] 
    displayName: Publish
    jobs:
      - job: Publish
        steps:
          - task: Bash@3
            inputs:
              targetType: "inline"
              workingDirectory: $(System.DefaultWorkingDirectory)
              script: |
                sed -i 's#ahmedavid/notedown-react:latest#ahmedavid/notedown-react:$(Build.BuildId)#' ./infra/app/client.yaml
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(System.DefaultWorkingDirectory)/infra/app"
              artifact: "notedown-kube-manifests"
              publishLocation: "pipeline"
