trigger:
  branches:
    include:
      - dev-*
  paths:
    include:
      - client/**

pool:
  name: ArmPool

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

stages:
  - stage: Test
    condition: 
    displayName: Test
    jobs:
      - job: TestJob
        steps:
          - task: Cache@2
            displayName: Cache NPM packages
            inputs:
              key: './client/package-lock.json'
              path: '$(npm_config_cache)'
          - task: Bash@3
            displayName: Clean Install
            inputs:
              targetType: "inline"
              script: "npm ci --cache $(npm_config_cache)"
              workingDirectory: "$(System.DefaultWorkingDirectory)/client"
          - task: Bash@3
            displayName: Run Tests
            inputs:
              targetType: "inline"
              script: "CI=true npm test"
              workingDirectory: "$(System.DefaultWorkingDirectory)/client"