trigger:
- none

pool:
  name: ArmPool

stages:
- stage: Test
  displayName: Run React Tests
  jobs:
  - job: TestJob
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'npm ci'
        workingDirectory: '$(System.DefaultWorkingDirectory)/client'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'CI=true npm test'
        workingDirectory: '$(System.DefaultWorkingDirectory)/client'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: |
          junit.xml
          **/*junit*.xml
        failTaskOnFailedTests: true
