apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notedown-react-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.davidahmadov.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notedown-react-server-svc
                port:
                  number: 3000
