apiVersion: apps/v1
kind: Deployment
metadata:
  name: notedown-react-server-depl
  namespace: notedown
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notedown-react-server
  template:
    metadata:
      labels:
        app: notedown-react-server
    spec:
      initContainers:
        - name: wait-for-postgresql
          image: busybox:latest
          command:
            ["sh", "-c", "until nc -z postgres-svc 5432; do sleep 5; done;"]
        - name: db-init
          image: ahmedavid/notedown-react-server:latest
          command: ["sh", "-c", "npx prisma db push"]
      containers:
        - name: notedown-react-server
          image: ahmedavid/notedown-react-server:latest
          ports:
            - containerPort: 3000

---
# postgres-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: notedown-react-server-svc
  namespace: notedown
spec:
  selector:
    app: notedown-react-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
