name: Tag Workflow
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag Name
        run: echo "The created tag is ${GITHUB_REF#refs/tags/}"
